# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d649e55fe1cdb18b249a6ed0cabc3b862537f060d2d100c1feab60304667ae3e5fa2794bbe48e25979781a1044cd12eb67cfd0093abdc6902728819de42a16c

test:
  secret_key_base: 25979f1ab684f5729f8d8c8aae002039fcaf0d449f94c106ffd90a5471f977bb2e1eb438d0496a3e95bc88ee674c264fead0bf4dc6991dec4069fca64d3e6feb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
